version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_UID: ${USER_UID}
                USER_GID: ${USER_GID}
                DOCKER_UID: ${DOCKER_UID}
        user: vscode
        working_dir: /workspace
        container_name: rtb-dev
        command: /bin/sh -c "sleep infinity"
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - type: volume
              source: vscode-server
              target: /home/vscode/.vscode-server
            - type: volume
              source: vscode-server-insiders
              target: /home/vscode/.vscode-server-insiders
            - type: bind
              source: ../
              target: /workspace
            - type: bind
              source: ~/.m2
              target: /home/vscode/.m2
        networks:
            - rtb
volumes:
    vscode-server:
    vscode-server-insiders:
networks:
    rtb:
